-- Plugin integrations live here so the core theme stays editor/syntax/LSP only.
-- Groups are set unconditionally; unused plugins simply never query them.

local function get(c)
  local ui = c.ui
  local s = c.syn
  local d = c.diag
  local g = c.git

  return {
    -- blink.cmp
    BlinkCmpMenu = { fg = ui.fg_ui, bg = ui.bg_menu },
    BlinkCmpMenuBorder = { fg = ui.border_strong, bg = ui.bg_menu },
    BlinkCmpMenuSelection = { fg = ui.white, bg = ui.picker_sel },
    BlinkCmpScrollBarThumb = { bg = ui.scroll },
    BlinkCmpScrollBarGutter = { bg = ui.bg_hover },
    BlinkCmpLabel = { fg = ui.fg_ui },
    BlinkCmpLabelMatch = { fg = ui.link, bold = true },
    BlinkCmpLabelDeprecated = { fg = ui.fg_muted, strikethrough = true },
    BlinkCmpLabelDetail = { fg = ui.fg_dim },
    BlinkCmpLabelDescription = { fg = ui.fg_dim },
    BlinkCmpSource = { fg = ui.fg_dim },
    BlinkCmpKind = { fg = s.func },
    BlinkCmpKindText = { fg = s.fg },
    BlinkCmpKindMethod = { fg = s.func },
    BlinkCmpKindFunction = { fg = s.func },
    BlinkCmpKindConstructor = { fg = s.type },
    BlinkCmpKindField = { fg = s.property },
    BlinkCmpKindVariable = { fg = s.variable },
    BlinkCmpKindClass = { fg = s.type },
    BlinkCmpKindInterface = { fg = s.type },
    BlinkCmpKindModule = { fg = s.module },
    BlinkCmpKindProperty = { fg = s.property },
    BlinkCmpKindUnit = { fg = s.number },
    BlinkCmpKindValue = { fg = s.constant },
    BlinkCmpKindEnum = { fg = s.type },
    BlinkCmpKindKeyword = { fg = s.keyword },
    BlinkCmpKindSnippet = { fg = s.decorator },
    BlinkCmpKindColor = { fg = s.func_builtin },
    BlinkCmpKindFile = { fg = ui.fg },
    BlinkCmpKindReference = { fg = s.constant },
    BlinkCmpKindFolder = { fg = ui.link },
    BlinkCmpKindEnumMember = { fg = s.constant },
    BlinkCmpKindConstant = { fg = s.constant },
    BlinkCmpKindStruct = { fg = s.type },
    BlinkCmpKindEvent = { fg = s.decorator },
    BlinkCmpKindOperator = { fg = s.operator },
    BlinkCmpKindTypeParameter = { fg = s.type },
    BlinkCmpKindCopilot = { fg = ui.accent },
    BlinkCmpDoc = { fg = ui.fg_ui, bg = ui.bg_menu },
    BlinkCmpDocBorder = { fg = ui.border_strong, bg = ui.bg_menu },
    BlinkCmpDocSeparator = { fg = ui.border, bg = ui.bg_menu },
    BlinkCmpSignatureHelp = { fg = ui.fg_ui, bg = ui.bg_menu },
    BlinkCmpSignatureHelpBorder = { fg = ui.border_strong, bg = ui.bg_menu },
    BlinkCmpSignatureHelpActiveParameter = { bg = ui.selection_word, bold = true },
    BlinkCmpGhostText = { fg = ui.fg_muted },

    -- nvim-cmp
    CmpItemAbbr = { fg = ui.fg_ui },
    CmpItemAbbrDeprecated = { fg = ui.fg_muted, strikethrough = true },
    CmpItemAbbrMatch = { fg = ui.link, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = ui.link },
    CmpItemKind = { fg = s.func },
    CmpItemMenu = { fg = ui.fg_dim },
    CmpItemKindText = { fg = s.fg },
    CmpItemKindMethod = { fg = s.func },
    CmpItemKindFunction = { fg = s.func },
    CmpItemKindConstructor = { fg = s.type },
    CmpItemKindField = { fg = s.property },
    CmpItemKindVariable = { fg = s.variable },
    CmpItemKindClass = { fg = s.type },
    CmpItemKindInterface = { fg = s.type },
    CmpItemKindModule = { fg = s.module },
    CmpItemKindProperty = { fg = s.property },
    CmpItemKindUnit = { fg = s.number },
    CmpItemKindValue = { fg = s.constant },
    CmpItemKindEnum = { fg = s.type },
    CmpItemKindKeyword = { fg = s.keyword },
    CmpItemKindSnippet = { fg = s.decorator },
    CmpItemKindColor = { fg = s.func_builtin },
    CmpItemKindFile = { fg = ui.fg },
    CmpItemKindReference = { fg = s.constant },
    CmpItemKindFolder = { fg = ui.link },
    CmpItemKindEnumMember = { fg = s.constant },
    CmpItemKindConstant = { fg = s.constant },
    CmpItemKindStruct = { fg = s.type },
    CmpItemKindEvent = { fg = s.decorator },
    CmpItemKindOperator = { fg = s.operator },
    CmpItemKindTypeParameter = { fg = s.type },

    -- telescope.nvim
    TelescopeNormal = { fg = ui.fg_ui, bg = ui.bg_menu },
    TelescopeBorder = { fg = ui.border, bg = ui.bg_menu },
    TelescopePromptNormal = { fg = ui.fg_ui, bg = ui.bg_menu },
    TelescopePromptBorder = { fg = ui.border_strong, bg = ui.bg_menu },
    TelescopePromptTitle = { fg = ui.white, bg = ui.accent_btn, bold = true },
    TelescopePromptPrefix = { fg = ui.accent },
    TelescopePromptCounter = { fg = ui.fg_dim },
    TelescopeResultsTitle = { fg = ui.fg_ui, bg = ui.bg_menu },
    TelescopePreviewTitle = { fg = ui.white, bg = ui.accent_badge },
    TelescopePreviewNormal = { fg = ui.fg, bg = ui.bg_chrome },
    TelescopePreviewBorder = { fg = ui.border, bg = ui.bg_chrome },
    TelescopeSelection = { fg = ui.white, bg = ui.picker_sel },
    TelescopeSelectionCaret = { fg = ui.white, bg = ui.picker_sel },
    TelescopeMatching = { fg = ui.link, bold = true },
    TelescopeMultiSelection = { fg = s.decorator },
    TelescopeMultiIcon = { fg = ui.accent },

    -- snacks.nvim
    SnacksNormal = { fg = ui.fg, bg = ui.bg },
    SnacksNormalNC = { fg = ui.fg, bg = ui.bg },
    SnacksWinBar = { fg = ui.fg_dim, bg = ui.bg_chrome },
    SnacksBackdrop = { bg = ui.bg },
    SnacksPicker = { fg = ui.fg_ui, bg = ui.bg_menu },
    SnacksPickerBorder = { fg = ui.border, bg = ui.bg_menu },
    SnacksPickerTitle = { fg = ui.fg_ui, bg = ui.bg_menu, bold = true },
    SnacksPickerPrompt = { fg = ui.accent },
    SnacksPickerInput = { fg = ui.fg_ui, bg = ui.bg_menu },
    SnacksPickerInputBorder = { fg = ui.accent_btn, bg = ui.bg_menu },
    SnacksPickerList = { fg = ui.fg_ui, bg = ui.bg_menu },
    SnacksPickerListCursorLine = { bg = ui.picker_sel, fg = ui.white },
    SnacksPickerMatch = { fg = ui.link, bold = true },
    SnacksPickerPreview = { fg = ui.fg, bg = ui.bg_chrome },
    SnacksPickerPreviewBorder = { fg = ui.border, bg = ui.bg_chrome },
    SnacksPickerDir = { fg = ui.link },
    SnacksPickerFile = { fg = ui.fg_ui },
    SnacksPickerGitStatusAdded = { fg = g.add },
    SnacksPickerGitStatusModified = { fg = g.change },
    SnacksPickerGitStatusDeleted = { fg = g.delete },
    SnacksPickerGitStatusUntracked = { fg = g.add },
    SnacksPickerGitStatusIgnored = { fg = g.ignore },
    SnacksNotifierInfo = { fg = d.info },
    SnacksNotifierWarn = { fg = d.warn },
    SnacksNotifierError = { fg = d.error },
    SnacksNotifierDebug = { fg = d.debug },
    SnacksNotifierTrace = { fg = ui.fg_dim },
    SnacksNotifierBorderInfo = { fg = d.info, bg = ui.bg_menu },
    SnacksNotifierBorderWarn = { fg = d.warn, bg = ui.bg_menu },
    SnacksNotifierBorderError = { fg = d.error, bg = ui.bg_menu },
    SnacksIndent = { fg = ui.indent },
    SnacksIndentScope = { fg = ui.indent_active },
    SnacksDashboardHeader = { fg = ui.accent },
    SnacksDashboardDesc = { fg = ui.fg_dim },
    SnacksDashboardIcon = { fg = ui.accent },
    SnacksDashboardKey = { fg = s.keyword },
    SnacksDashboardFooter = { fg = ui.fg_dim },
    SnacksDashboardSpecial = { fg = s.func },

    -- bufferline.nvim
    BufferLineFill = { bg = ui.bg_chrome },
    BufferLineBackground = { fg = ui.fg_dim, bg = ui.bg_menu },
    BufferLineBuffer = { fg = ui.fg_dim, bg = ui.bg_menu },
    BufferLineBufferVisible = { fg = ui.fg_dim, bg = ui.bg_chrome },
    BufferLineBufferSelected = { fg = ui.fg_ui, bg = ui.bg, bold = true },
    BufferLineIndicatorSelected = { fg = ui.accent, bg = ui.bg },
    BufferLineIndicatorVisible = { fg = ui.bg_chrome, bg = ui.bg_chrome },
    BufferLineSeparator = { fg = ui.bg_chrome, bg = ui.bg_menu },
    BufferLineSeparatorVisible = { fg = ui.bg_chrome, bg = ui.bg_chrome },
    BufferLineSeparatorSelected = { fg = ui.bg_chrome, bg = ui.bg },
    BufferLineModified = { fg = g.change, bg = ui.bg_menu },
    BufferLineModifiedVisible = { fg = g.change, bg = ui.bg_chrome },
    BufferLineModifiedSelected = { fg = g.change, bg = ui.bg },
    BufferLineCloseButton = { fg = ui.fg_dim, bg = ui.bg_menu },
    BufferLineCloseButtonSelected = { fg = ui.fg_ui, bg = ui.bg },
    BufferLineTab = { fg = ui.fg_dim, bg = ui.bg_menu },
    BufferLineTabSelected = { fg = ui.fg_ui, bg = ui.bg },
    BufferLineTabClose = { fg = d.error, bg = ui.bg_chrome },
    BufferLineDuplicate = { fg = ui.fg_muted, bg = ui.bg_menu, italic = true },
    BufferLineDuplicateSelected = { fg = ui.fg_dim, bg = ui.bg, italic = true },
    BufferLineError = { fg = d.error, bg = ui.bg_menu },
    BufferLineErrorSelected = { fg = d.error, bg = ui.bg },
    BufferLineWarning = { fg = d.warn, bg = ui.bg_menu },
    BufferLineWarningSelected = { fg = d.warn, bg = ui.bg },
    BufferLineInfo = { fg = d.info, bg = ui.bg_menu },
    BufferLineInfoSelected = { fg = d.info, bg = ui.bg },
    BufferLineHint = { fg = d.hint, bg = ui.bg_menu },
    BufferLineHintSelected = { fg = d.hint, bg = ui.bg },
    BufferLineOffsetSeparator = { fg = ui.border, bg = ui.bg_chrome },

    -- which-key.nvim
    WhichKey = { fg = s.keyword },
    WhichKeyGroup = { fg = s.func },
    WhichKeyDesc = { fg = ui.fg },
    WhichKeySeparator = { fg = ui.fg_dim },
    WhichKeyFloat = { bg = ui.bg_menu },
    WhichKeyBorder = { fg = ui.border, bg = ui.bg_menu },
    WhichKeyValue = { fg = ui.fg_dim },
    WhichKeyIcon = { fg = ui.accent },
    WhichKeyNormal = { fg = ui.fg_ui, bg = ui.bg_menu },
    WhichKeyTitle = { fg = ui.fg_ui, bold = true },

    -- nvim-tree / neo-tree
    NvimTreeNormal = { fg = ui.fg_ui, bg = ui.bg_chrome },
    NvimTreeNormalNC = { fg = ui.fg_ui, bg = ui.bg_chrome },
    NvimTreeWinSeparator = { fg = ui.border, bg = ui.bg_chrome },
    NvimTreeEndOfBuffer = { fg = ui.bg_chrome },
    NvimTreeRootFolder = { fg = ui.fg_ui, bold = true },
    NvimTreeFolderName = { fg = ui.fg_ui },
    NvimTreeFolderIcon = { fg = ui.link },
    NvimTreeOpenedFolderName = { fg = ui.fg_ui, bold = true },
    NvimTreeEmptyFolderName = { fg = ui.fg_dim },
    NvimTreeIndentMarker = { fg = ui.border },
    NvimTreeGitDirty = { fg = g.change },
    NvimTreeGitNew = { fg = g.add },
    NvimTreeGitDeleted = { fg = g.delete },
    NvimTreeGitIgnored = { fg = g.ignore },
    NvimTreeGitStaged = { fg = g.add },
    NvimTreeGitMerge = { fg = g.conflict },
    NvimTreeSpecialFile = { fg = s.decorator },
    NvimTreeExecFile = { fg = s.quote },
    NvimTreeImageFile = { fg = s.func },
    NvimTreeSymlink = { fg = ui.link },

    NeoTreeNormal = { fg = ui.fg_ui, bg = ui.bg_chrome },
    NeoTreeNormalNC = { fg = ui.fg_ui, bg = ui.bg_chrome },
    NeoTreeWinSeparator = { fg = ui.border, bg = ui.bg_chrome },
    NeoTreeRootName = { fg = ui.fg_ui, bold = true },
    NeoTreeDirectoryName = { fg = ui.fg_ui },
    NeoTreeDirectoryIcon = { fg = ui.link },
    NeoTreeFileName = { fg = ui.fg_ui },
    NeoTreeFileNameOpened = { fg = ui.fg_bright, bold = true },
    NeoTreeIndentMarker = { fg = ui.border },
    NeoTreeGitAdded = { fg = g.add },
    NeoTreeGitModified = { fg = g.change },
    NeoTreeGitDeleted = { fg = g.delete },
    NeoTreeGitConflict = { fg = g.conflict },
    NeoTreeGitUntracked = { fg = g.add },
    NeoTreeGitIgnored = { fg = g.ignore },
    NeoTreeFloatBorder = { fg = ui.border, bg = ui.bg_menu },
    NeoTreeTitleBar = { fg = ui.fg_ui, bg = ui.bg_hover },

    -- lazy.nvim / mason
    LazyNormal = { fg = ui.fg_ui, bg = ui.bg_menu },
    LazyButton = { fg = ui.fg_ui, bg = ui.bg_hover },
    LazyButtonActive = { fg = ui.white, bg = ui.accent_btn },
    LazyH1 = { fg = ui.white, bg = ui.accent_btn, bold = true },
    LazyH2 = { fg = s.heading, bold = true },
    LazyComment = { fg = s.comment },
    LazyProp = { fg = ui.fg_dim },
    LazyValue = { fg = s.constant },
    LazyUrl = { fg = ui.link, underline = true },
    LazySpecial = { fg = ui.accent },
    LazyReasonPlugin = { fg = s.func },
    LazyReasonRuntime = { fg = s.type },
    LazyReasonEvent = { fg = s.decorator },
    LazyReasonStart = { fg = s.quote },
    LazyReasonCmd = { fg = s.keyword },
    LazyReasonFt = { fg = s.constant },
    LazyReasonKeys = { fg = s.keyword_control },
    LazyReasonSource = { fg = s.string },
    LazyProgressDone = { fg = s.quote },
    LazyProgressTodo = { fg = ui.fg_muted },

    MasonNormal = { fg = ui.fg_ui, bg = ui.bg_menu },
    MasonHeader = { fg = ui.white, bg = ui.accent_btn, bold = true },
    MasonHeaderSecondary = { fg = ui.white, bg = ui.accent_badge },
    MasonHighlight = { fg = ui.accent },
    MasonHighlightBlock = { fg = ui.white, bg = ui.accent_btn },
    MasonMuted = { fg = ui.fg_dim },
    MasonMutedBlock = { fg = ui.fg_dim, bg = ui.bg_hover },

    -- indent-blankline
    IblIndent = { fg = ui.indent },
    IblScope = { fg = ui.indent_active },
    IndentBlanklineChar = { fg = ui.indent },
    IndentBlanklineContextChar = { fg = ui.indent_active },

    -- nvim-notify
    NotifyBackground = { bg = ui.bg_menu },
    NotifyERRORBorder = { fg = d.error, bg = ui.bg_menu },
    NotifyWARNBorder = { fg = d.warn, bg = ui.bg_menu },
    NotifyINFOBorder = { fg = d.info, bg = ui.bg_menu },
    NotifyDEBUGBorder = { fg = d.debug, bg = ui.bg_menu },
    NotifyTRACEBorder = { fg = ui.fg_dim, bg = ui.bg_menu },
    NotifyERRORIcon = { fg = d.error },
    NotifyWARNIcon = { fg = d.warn_icon },
    NotifyINFOIcon = { fg = d.info },
    NotifyDEBUGIcon = { fg = d.debug },
    NotifyTRACEIcon = { fg = ui.fg_dim },
    NotifyERRORTitle = { fg = d.error },
    NotifyWARNTitle = { fg = d.warn },
    NotifyINFOTitle = { fg = d.info },
    NotifyDEBUGTitle = { fg = d.debug },
    NotifyTRACETitle = { fg = ui.fg_dim },
    NotifyERRORBody = { fg = ui.fg_ui, bg = ui.bg_menu },
    NotifyWARNBody = { fg = ui.fg_ui, bg = ui.bg_menu },
    NotifyINFOBody = { fg = ui.fg_ui, bg = ui.bg_menu },
    NotifyDEBUGBody = { fg = ui.fg_ui, bg = ui.bg_menu },
    NotifyTRACEBody = { fg = ui.fg_ui, bg = ui.bg_menu },

    -- trouble.nvim
    TroubleNormal = { fg = ui.fg, bg = ui.bg_chrome },
    TroubleNormalNC = { fg = ui.fg, bg = ui.bg_chrome },
    TroubleText = { fg = ui.fg },
    TroubleCount = { fg = ui.fg_ui, bg = ui.bg_hover },
    TroubleFile = { fg = ui.link },
    TroubleFoldIcon = { fg = ui.fg_dim },
    TroubleLocation = { fg = ui.fg_dim },
    TroublePreview = { bg = ui.hover },
    TroubleSource = { fg = ui.fg_dim },
    TroubleCode = { fg = s.constant },

    -- flash.nvim
    FlashBackdrop = { fg = ui.fg_muted },
    FlashMatch = { bg = ui.find_other },
    FlashCurrent = { fg = ui.white, bg = ui.accent },
    FlashLabel = { fg = ui.white, bg = s.keyword, bold = true },

    -- mini.nvim (stable subset)
    MiniIndentscopeSymbol = { fg = ui.indent_active },
    MiniStatuslineModeNormal = { fg = ui.white, bg = ui.accent_btn, bold = true },
    MiniStatuslineModeInsert = { fg = ui.white, bg = g.add, bold = true },
    MiniStatuslineModeVisual = { fg = ui.white, bg = s.func, bold = true },
    MiniStatuslineModeReplace = { fg = ui.white, bg = s.keyword, bold = true },
    MiniStatuslineModeCommand = { fg = ui.bg, bg = s.decorator, bold = true },
    MiniStatuslineDevinfo = { fg = ui.fg_dim, bg = ui.bg_hover },
    MiniStatuslineFilename = { fg = ui.fg, bg = ui.bg_chrome },
    MiniStatuslineFileinfo = { fg = ui.fg_dim, bg = ui.bg_hover },
    MiniStatuslineInactive = { fg = ui.fg_muted, bg = ui.bg_chrome },
    MiniTablineCurrent = { fg = ui.fg_ui, bg = ui.bg, bold = true },
    MiniTablineVisible = { fg = ui.fg_dim, bg = ui.bg_chrome },
    MiniTablineHidden = { fg = ui.fg_dim, bg = ui.bg_menu },
    MiniTablineFill = { bg = ui.bg_chrome },
    MiniCursorword = { bg = ui.selection_word },
    MiniCursorwordCurrent = { bg = ui.selection_word },
    MiniDiffSignAdd = { fg = g.add_gutter },
    MiniDiffSignChange = { fg = g.change_gutter },
    MiniDiffSignDelete = { fg = g.delete_gutter },
    MiniHipatternsFixme = { fg = ui.white, bg = d.error, bold = true },
    MiniHipatternsHack = { fg = ui.bg, bg = d.warn, bold = true },
    MiniHipatternsTodo = { fg = ui.white, bg = d.info, bold = true },
    MiniHipatternsNote = { fg = ui.white, bg = d.hint, bold = true },

    -- oil.nvim
    OilDir = { fg = ui.link, bold = true },
    OilDirIcon = { fg = ui.link },
    OilLink = { fg = s.func },
    OilLinkTarget = { fg = ui.fg_dim },
    OilCreate = { fg = g.add },
    OilDelete = { fg = g.delete },
    OilChange = { fg = g.change },
    OilCopy = { fg = s.constant },
    OilMove = { fg = s.decorator },

    -- fzf-lua
    FzfLuaNormal = { fg = ui.fg_ui, bg = ui.bg_menu },
    FzfLuaBorder = { fg = ui.border, bg = ui.bg_menu },
    FzfLuaTitle = { fg = ui.fg_ui, bold = true },
    FzfLuaPreviewNormal = { fg = ui.fg, bg = ui.bg_chrome },
    FzfLuaPreviewBorder = { fg = ui.border, bg = ui.bg_chrome },
    FzfLuaCursorLine = { bg = ui.picker_sel, fg = ui.white },
    FzfLuaMatch = { fg = ui.link, bold = true },
    FzfLuaPathLineNr = { fg = ui.linenr },
    FzfLuaPathColNr = { fg = ui.fg_dim },

    -- nvim-dap
    DapBreakpoint = { fg = d.error },
    DapBreakpointCondition = { fg = d.warn },
    DapLogPoint = { fg = d.info },
    DapStopped = { fg = s.quote },
    DapStoppedLine = { bg = c.git.add_bg },
    DapUIVariable = { fg = s.variable },
    DapUIScope = { fg = s.type },
    DapUIType = { fg = s.type },
    DapUIValue = { fg = s.constant },
    DapUIModifiedValue = { fg = s.decorator, bold = true },
    DapUIDecoration = { fg = ui.accent },
    DapUIBreakpointsPath = { fg = ui.link },
    DapUIBreakpointsLine = { fg = ui.linenr },
    DapUIBreakpointsInfo = { fg = d.info },
    DapUIWatchesEmpty = { fg = ui.fg_muted },
    DapUIWatchesValue = { fg = s.constant },
    DapUIWatchesError = { fg = d.error },
    DapUIStop = { fg = d.error },
    DapUIPlayPause = { fg = g.add },
    DapUIRestart = { fg = g.add },
    DapUIStepOver = { fg = ui.accent },
    DapUIStepInto = { fg = ui.accent },
    DapUIStepBack = { fg = ui.accent },
    DapUIStepOut = { fg = ui.accent },

    -- illuminate / cursor word
    IlluminatedWordText = { bg = ui.selection_word },
    IlluminatedWordRead = { bg = ui.selection_word },
    IlluminatedWordWrite = { bg = ui.find_other },

    -- leap / hop
    LeapMatch = { fg = ui.white, bg = ui.accent, bold = true },
    LeapLabelPrimary = { fg = ui.white, bg = s.keyword, bold = true },
    LeapLabelSecondary = { fg = ui.white, bg = s.func, bold = true },
    HopNextKey = { fg = s.keyword, bold = true },
    HopNextKey1 = { fg = ui.accent, bold = true },
    HopNextKey2 = { fg = ui.link },
    HopUnmatched = { fg = ui.fg_muted },

    -- alpha / dashboard
    AlphaHeader = { fg = ui.accent },
    AlphaButtons = { fg = ui.fg_ui },
    AlphaShortcut = { fg = s.keyword },
    AlphaFooter = { fg = ui.fg_dim },

    -- navic
    NavicText = { fg = ui.fg_dim },
    NavicSeparator = { fg = ui.fg_muted },
    NavicIconsFile = { fg = ui.fg },
    NavicIconsModule = { fg = s.module },
    NavicIconsNamespace = { fg = s.module },
    NavicIconsPackage = { fg = s.module },
    NavicIconsClass = { fg = s.type },
    NavicIconsMethod = { fg = s.func },
    NavicIconsProperty = { fg = s.property },
    NavicIconsField = { fg = s.property },
    NavicIconsConstructor = { fg = s.type },
    NavicIconsEnum = { fg = s.type },
    NavicIconsInterface = { fg = s.type },
    NavicIconsFunction = { fg = s.func },
    NavicIconsVariable = { fg = s.variable },
    NavicIconsConstant = { fg = s.constant },
    NavicIconsString = { fg = s.string },
    NavicIconsNumber = { fg = s.number },
    NavicIconsBoolean = { fg = s.boolean },
    NavicIconsArray = { fg = s.property },
    NavicIconsObject = { fg = s.type },
    NavicIconsKey = { fg = s.keyword },
    NavicIconsNull = { fg = s.boolean },
    NavicIconsEnumMember = { fg = s.constant },
    NavicIconsStruct = { fg = s.type },
    NavicIconsEvent = { fg = s.decorator },
    NavicIconsOperator = { fg = s.operator },
    NavicIconsTypeParameter = { fg = s.type },
  }
end

return { get = get }
