-- Language-specific groups. Colors still come from the shared palettes;
-- these only apply more specific TextMate/Treesitter mappings.

local function get(c)
  local s = c.syn
  return {
    -- Markdown (legacy + html)
    markdownH1 = { fg = s.heading, bold = true },
    markdownH2 = { fg = s.heading, bold = true },
    markdownH3 = { fg = s.heading, bold = true },
    markdownH4 = { fg = s.heading, bold = true },
    markdownH5 = { fg = s.heading, bold = true },
    markdownH6 = { fg = s.heading, bold = true },
    markdownHeadingDelimiter = { fg = s.heading, bold = true },
    markdownCode = { fg = s.raw },
    markdownCodeBlock = { fg = s.fg },
    markdownCodeDelimiter = { fg = s.raw },
    markdownBlockquote = { fg = s.quote },
    markdownListMarker = { fg = s.list },
    markdownOrderedListMarker = { fg = s.list },
    markdownUrl = { fg = c.ui.link, underline = true },
    markdownLinkText = { fg = s.link_text },
    markdownItalic = { fg = s.fg, italic = true },
    markdownBold = { fg = s.fg, bold = true },

    htmlTag = { fg = s.tag_delimiter },
    htmlEndTag = { fg = s.tag_delimiter },
    htmlTagName = { fg = s.tag },
    htmlArg = { fg = s.attribute },
    htmlTitle = { fg = s.fg, bold = true },
    htmlLink = { fg = c.ui.link, underline = true },
    htmlSpecialTagName = { fg = s.tag },
    htmlString = { fg = s.string },

    ['@tag.tsx'] = { fg = s.tag },
    ['@tag.jsx'] = { fg = s.tag },
    ['@constructor.tsx'] = { fg = s.tag },
    ['@constructor.javascript'] = { fg = s.type },
    ['@tag.delimiter.tsx'] = { fg = s.tag_delimiter },
    ['@tag.delimiter.jsx'] = { fg = s.tag_delimiter },
    ['@tag.attribute.tsx'] = { fg = s.attribute },
    ['@tag.attribute.javascript'] = { fg = s.attribute },
    ['@punctuation.special.javascript'] = { fg = s.embedded },
    ['@punctuation.special.typescript'] = { fg = s.embedded },
    ['@punctuation.special.tsx'] = { fg = s.embedded },

    jsonKeyword = { fg = s.json_key },
    jsonString = { fg = s.string },
    jsonNumber = { fg = s.number },
    jsonBoolean = { fg = s.boolean },
    jsonNull = { fg = s.boolean },
    jsonQuote = { fg = s.string },
    ['@property.json'] = { fg = s.json_key },
    ['@label.json'] = { fg = s.json_key },

    cssTagName = { fg = s.css_class },
    cssClassName = { fg = s.css_class },
    cssClassNameDot = { fg = s.css_class },
    cssIdentifier = { fg = s.css_class },
    cssProp = { fg = s.css_property },
    cssAttr = { fg = s.string },
    cssAttrComma = { fg = s.punctuation },
    cssBraces = { fg = s.punctuation },
    cssColor = { fg = s.number },
    cssUnitDecorators = { fg = s.number },
    cssImportant = { fg = s.keyword },
    cssFunctionName = { fg = s.func_builtin },
    cssVendor = { fg = s.css_property },
    ['@property.css'] = { fg = s.css_property },
    ['@type.css'] = { fg = s.css_class },
    ['@type.definition.css'] = { fg = s.css_class },
    ['@attribute.css'] = { fg = s.css_class },
    ['@variable.css'] = { fg = s.parameter },
    ['@function.css'] = { fg = s.func_builtin },

    ['@type.builtin.typescript'] = { fg = s.type },
    ['@type.builtin.tsx'] = { fg = s.type },
    ['@variable.builtin.typescript'] = { fg = s.constant },
    ['@lsp.typemod.variable.local.typescript'] = { fg = s.variable },
    ['@lsp.typemod.variable.local.javascript'] = { fg = s.variable },
    ['@lsp.type.interface.typescript'] = { fg = s.type },
    ['@lsp.type.class.typescript'] = { fg = s.type },

    ['@type.builtin.go'] = { fg = s.type },
    ['@module.go'] = { fg = s.module },
    ['@variable.member.go'] = { fg = s.property },
    ['@function.builtin.go'] = { fg = s.func_builtin },
    ['@lsp.type.type.go'] = { fg = s.type },
    ['@lsp.type.namespace.go'] = { fg = s.module },

    ['@lsp.type.macro.rust'] = { fg = s.macro },
    ['@lsp.typemod.macro.defaultLibrary.rust'] = { fg = s.macro },
    ['@lsp.type.selfKeyword.rust'] = { fg = s.constant },
    ['@lsp.type.selfTypeKeyword.rust'] = { fg = s.type },
    ['@lsp.type.lifetime.rust'] = { fg = s.parameter },
    ['@lsp.type.builtinType.rust'] = { fg = s.type },
    ['@lsp.type.keyword.rust'] = { fg = s.keyword },
    ['@lsp.typemod.keyword.controlFlow.rust'] = { fg = s.keyword_control },
    ['@lsp.type.decorator.rust'] = { fg = s.decorator },
    ['@lsp.type.interface.rust'] = { fg = s.type },
    ['@function.macro.rust'] = { fg = s.macro },
    ['@attribute.rust'] = { fg = s.decorator },
    ['@type.builtin.rust'] = { fg = s.type },
    ['@keyword.import.rust'] = { fg = s.keyword_control },
    ['@module.rust'] = { fg = s.module },
    ['@punctuation.special.rust'] = { fg = s.parameter },

    ['@variable.builtin.python'] = { fg = s.constant },
    ['@attribute.python'] = { fg = s.decorator },
    ['@function.builtin.python'] = { fg = s.func_builtin },
    ['@type.builtin.python'] = { fg = s.type },
    ['@constructor.python'] = { fg = s.type },
    ['@keyword.import.python'] = { fg = s.keyword_control },
    ['@lsp.type.class.python'] = { fg = s.type },
    ['@lsp.type.decorator.python'] = { fg = s.decorator },

    javaKeyword = { fg = s.keyword },
    javaType = { fg = s.fg }, -- storage.type.java -> syntax fg
    javaOperator = { fg = s.operator },
    javaAnnotation = { fg = s.decorator },
    ['@type.builtin.java'] = { fg = s.fg },
    ['@attribute.java'] = { fg = s.decorator },
    ['@lsp.type.annotation.java'] = { fg = s.decorator },
    ['@lsp.type.modifier.java'] = { fg = s.keyword_modifier },
    ['@keyword.import.java'] = { fg = s.fg }, -- storage.modifier.import
    ['@module.java'] = { fg = s.fg },

    cType = { fg = s.type },
    cStorageClass = { fg = s.keyword },
    cInclude = { fg = s.preprocessor },
    cDefine = { fg = s.preprocessor },
    cPreCondit = { fg = s.preprocessor },
    cppType = { fg = s.type },
    cppStatement = { fg = s.keyword_control },
    ['@type.builtin.c'] = { fg = s.type },
    ['@type.builtin.cpp'] = { fg = s.type },
    ['@keyword.directive.c'] = { fg = s.preprocessor },
    ['@keyword.directive.cpp'] = { fg = s.preprocessor },
    ['@keyword.import.c'] = { fg = s.preprocessor },
    ['@keyword.import.cpp'] = { fg = s.preprocessor },
    ['@lsp.type.macro.c'] = { fg = s.macro },
    ['@lsp.type.macro.cpp'] = { fg = s.macro },
    ['@lsp.type.class.cpp'] = { fg = s.type },
    ['@keyword.operator.cpp'] = { fg = s.keyword_control }, -- new/delete

    luaFunction = { fg = s.keyword },
    luaTable = { fg = s.punctuation },
    ['@variable.builtin.lua'] = { fg = s.constant },
    ['@function.builtin.lua'] = { fg = s.func_builtin },
    ['@module.builtin.lua'] = { fg = s.module },
    ['@constructor.lua'] = { fg = s.punctuation },
    ['@lsp.typemod.variable.global.lua'] = { fg = s.constant },
    ['@lsp.typemod.variable.defaultLibrary.lua'] = { fg = s.constant },

    sqlKeyword = { fg = s.keyword_control },
    sqlFunction = { fg = s.func_builtin },
    sqlType = { fg = s.type },
    sqlOperator = { fg = s.keyword_modifier },
    sqlSpecial = { fg = s.boolean },
    ['@keyword.sql'] = { fg = s.keyword_control },
    ['@type.sql'] = { fg = s.type },
    ['@function.sql'] = { fg = s.func_builtin },
    ['@attribute.sql'] = { fg = s.constant },
  }
end

return { get = get }
